---
title: "Exploratory Data Analysis"
author: "Joe Kosteck"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Exploratory Data Analysis

```{r, warning=FALSE, message=FALSE}
library(tidycensus)
library(tidyverse)
library(ggmap)
library(viridis)
library(leaflet)
library(ZillowR)
library(rgdal)
library(lubridate)
library(scales)
```

```{r}
#5-year American Community Survey 2015
#Info Here: https://walkerke.github.io/tidycensus/
acs2017Variables <- load_variables(2017, "acs5", cache = TRUE)
```

```{r, eval=FALSE}
censusVars <- c(
  `Total Population` = "B01003_001",
  `Total Housing Units` = "B25001_001",
  `Total Occupied Housing Units` = "B25002_002",
  `Total Vacant Housing Units` = "B25002_003",
  `Total Owner-Occupied Units` = "B25003_002",
  `Total Renter-Occupied Units` = "B25003_003",
  `Total For-Rent Units` = "B25004_002",
  `Total Rented Non-Occ Units` = "B25004_003",
  `Total For-Sale Units` = "B25004_004",
  `Total Sold Non-Occ Units` = "B25004_005",
  `Med Rent/Income%` = "B25071_001",
  `25% Owner Occ Housing Val` = "B25076_001",
  `50% Owner Occ Housing Val` = "B25077_001",
  `75% Owner Occ Housing Val` = "B25078_001",
  `Med Owner Costs-Mortgage` = "B25088_002",
  `Med Owner Costs-No Mortgage` = "B25088_003",
  `Med Costs/Income%-Mortgage` = "B25092_002",
  `Med Costs/Income%-No Mortgage` = "B25092_003",
  `Med Monthly Housing Costs` = "B25105_001",
  `Med Family Income` = "B19113_001"
)

stJoesTract <- get_acs(
  geography = "tract",
  variables = censusVars,
  state = "IN",
  county = "St. Joseph County",
  output = "wide",
  geometry = TRUE
)


stJoesBlockGroup <- get_acs(
  geography = "block group",
  variables = censusVars,
  state = "IN",
  county = "St. Joseph County",
  output = "wide",
  geometry = TRUE
)

stJoesTract <- sf::st_transform(stJoesTract, 4326)
stJoesBlockGroup <- sf::st_transform(stJoesBlockGroup, 4326)
```

```{r, eval=FALSE}
zillowNeighborhoods <- readOGR(dsn = "C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources",
                               layer = "ZillowNeighborhoods-IN",
                               stringsAsFactors = F)
```

```{r, eval=FALSE}
stJoesZillow <- zillowNeighborhoods[zillowNeighborhoods$County == "Saint Joseph", ]
````

```{r, eval=FALSE}
save.image("EDA Data.RData")
```

```{r}
load("EDA Data.RData")
```

##Boundaries
```{r}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = stJoesTract,
              color = "black",
              opacity = .6,
              weight = 2,
              fill = FALSE,
              popup = ~NAME,
              group = "Census Tract") %>%
  addPolygons(data = stJoesBlockGroup,
              color = "blue",
              opacity = .6,
              weight = 2,
              fill = FALSE,
              popup = ~NAME,
              group = "Census Block Group") %>%
  addPolygons(data = stJoesZillow,
              color = "red",
              opacity = .6,
              weight = 2,
              fill = FALSE,
              group = "Zillow") %>%
  addLayersControl(
    baseGroups = c("Census Tract", "Census Block Group", "Zillow"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

##Census Data Explorer
```{r}
populationPal <- colorNumeric("Blues", stJoesTract$`Total PopulationE`)
totalHousingPal <- colorNumeric("Blues", stJoesTract$`Total Housing UnitsE`)
totalRentalUnitsPal <- colorNumeric("Blues", stJoesTract$`Total Renter-Occupied UnitsE`)
incomePal <- colorNumeric("Blues", stJoesTract$`Med Family IncomeE`)
housingCostPal <- colorNumeric("Blues", stJoesTract$`Med Monthly Housing CostsE`)
rentIncomePal <- colorNumeric("Blues", stJoesTract$`Med Rent/Income%E`)

mapPopup <- paste0("<b>",
                   stJoesTract$NAME,
                   "</b><br>Total Population: ",
                   stJoesTract$`Total PopulationE`,
                   "<br>Total Housing Units: ",
                   stJoesTract$`Total Housing UnitsE`,
                   "<br> Median Family Income: $",
                   stJoesTract$`Med Family IncomeE`,
                   "<br>Total Rental Units: ",
                   stJoesTract$`Total Renter-Occupied UnitsE`,
                   "<br>Median Monthly Housing Costs: $",
                   stJoesTract$`Med Monthly Housing CostsE`,
                   "<br>Median Percent of Income Spent on Rent: ",
                   stJoesTract$`Med Rent/Income%E`, "%")

leaflet() %>%
  addTiles() %>%
  addPolygons(data = stJoesTract,
              color = ~populationPal(`Total PopulationE`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Total Population") %>%
  addLegend(title = "Population",
            position = "bottomleft",
            pal = populationPal,
            values = stJoesTract$`Total PopulationE`,
            group = "Total Population") %>%
  addPolygons(data = stJoesTract,
              color = ~totalHousingPal(`Total Housing UnitsE`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Total Housing Units") %>%
  addLegend(title = "Housing Units",
            position = "bottomleft",
            pal = totalHousingPal,
            values = stJoesTract$`Total Housing UnitsE`,
            group = "Total Housing Units") %>%
  addPolygons(data = stJoesTract,
              color = ~incomePal(`Med Family IncomeE`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Median Family Income") %>%
  addLegend(title = "Family Income",
            position = "bottomleft",
            pal = incomePal,
            values = stJoesTract$`Med Family IncomeE`,
            group = "Median Family Income") %>%
  addPolygons(data = stJoesTract,
              color = ~totalRentalUnitsPal(`Total Renter-Occupied UnitsE`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Total Rental Units") %>%
  addLegend(title = "Rental Units",
            position = "bottomleft",
            pal = totalRentalUnitsPal,
            values = stJoesTract$`Total Renter-Occupied UnitsE`,
            group = "Total Rental Units") %>%
  addPolygons(data = stJoesTract,
              color = ~housingCostPal(`Med Monthly Housing CostsE`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Median Housing Costs") %>%
  addLegend(title = "Housing Costs",
            position = "bottomleft",
            pal = housingCostPal,
            values = stJoesTract$`Med Monthly Housing CostsE`,
            group = "Median Housing Costs") %>%
  addPolygons(data = stJoesTract,
              color = ~rentIncomePal(`Med Rent/Income%E`),
              opacity = .6,
              weight = 2,
              popup = mapPopup,
              group = "Median Rent/Income") %>%
  addLegend(title = "Rent/Income",
            position = "bottomleft",
            pal = rentIncomePal,
            values = stJoesTract$`Med Rent/Income%E`,
            group = "Median Rent/Income") %>%
  addLayersControl(
    overlayGroups = c("Total Population", "Total Housing Units", "Median Family Income", "Total Rental Units",
                      "Median Housing Costs", "Median Rent/Income"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  hideGroup(c("Total Housing Units", "Median Family Income", "Total Rental Units", "Median Housing Costs",
              "Median Rent/Income"))

```

```{r}
mortgageCosts <- stJoesTract %>%
  select(-geometry) %>%
  as.tibble() %>%
  select(NAME, `Med Owner Costs-MortgageE`, `Med Owner Costs-No MortgageE`) %>%
  gather(key = "Mortgage Status", value = "Cost", `Med Owner Costs-MortgageE`:`Med Owner Costs-No MortgageE`) %>%
  mutate(`Mortgage Status` = ifelse(`Mortgage Status` == "Med Owner Costs-MortgageE", "Mortgage", "No Mortgage"))
```

```{r}
ggplot(
  data = mortgageCosts,
  aes(x = `Mortgage Status`, y = Cost)
) + geom_boxplot() + labs(x = "Mortgage Status",
                          title = "Monthly Home Ownership Costs") +
   scale_y_continuous(labels = dollar_format())
```
```{r}

```

##Zillow Time Series Data
```{r, message=FALSE}
neighborhoodRent <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/Neighborhood Rent Prices-Zillow.csv",
                             stringsAsFactors = F) %>%
  filter(State == "IN") %>%
  filter(CountyName == "Saint Joseph County")
```

```{r}
longRentZillow <- neighborhoodRent %>%
  gather(key = DateString,
         value = "ZRI",
         -c(RegionID, RegionName, City, State, Metro, CountyName, SizeRank))

tidyRentZillow <- longRentZillow %>%
  mutate(DateString = str_sub(DateString, start = 2)) %>%
  mutate(Date = as.Date(paste0(DateString, ".1"), "%Y.%m.%d") + months(1) - days(1))
```

```{r}
ggplot(
  data = tidyRentZillow,
  aes(x = Date, y = ZRI, color = RegionName)
) + geom_point() + scale_y_continuous(labels = dollar_format()) +
  labs(x = "Date", y = "Zillow Rent Index",
       title = "Rent Over Time in South Bend Neighborhoods")
```

```{r}
homeValueIndex <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/Zillow Home Value Index - All Homes.csv",
                           stringsAsFactors = F) %>%
  filter(State == "IN") %>%
  filter(CountyName == "Saint Joseph County")
```

```{r}
longValueZillow <- homeValueIndex %>%
  gather(key = DateString,
         value = "ZHVI",
         -c(RegionID, RegionName, City, State, Metro, CountyName, SizeRank))

tidyValueZillow <- longValueZillow %>%
  mutate(DateString = str_sub(DateString, start = 2)) %>%
  mutate(Date = as.Date(paste0(DateString, ".1"), "%Y.%m.%d") + months(1) - days(1))
```

```{r}
ggplot(
  data = tidyValueZillow,
  aes(x = Date, y = ZHVI, color = RegionName)
) + geom_point() + scale_y_continuous(labels = dollar_format()) +
  labs(x = "Date", y = "Zillow Home Value Index",
       title = "Housing Prices Over Time in South Bend Neighborhoods")
```

```{r}
homeSales <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/Sale_Counts_Seas_Adj_City.csv",
                           stringsAsFactors = F) %>%
  filter(StateName == "Indiana") %>%
  filter(RegionName == "South Bend")
```

```{r}
longSalesZillow <- homeSales %>%
  gather(key = DateString,
         value = "Homes Sold",
         -c(RegionID, RegionName, StateName, SizeRank))

tidySalesZillow <- longSalesZillow %>%
  mutate(DateString = str_sub(DateString, start = 2)) %>%
  mutate(Date = as.Date(paste0(DateString, ".1"), "%Y.%m.%d") + months(1) - days(1))
```

```{r}
ggplot(
  data = na.omit(tidySalesZillow),
  aes(x = Date, y = `Homes Sold`)
) + geom_point() +
  labs(x = "Date", y = "Homes",
       title = "Homes Sold Over Time in South Bend")
```

```{r}
bottomTier <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/City/City_Zhvi_BottomTier.csv",
         stringsAsFactors = F) %>%
  filter(State == "IN") %>%
  filter(Metro == "South Bend-Mishawaka")

middleTier <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/City/City_Zhvi_MiddleTier.csv",
         stringsAsFactors = F) %>%
  filter(State == "IN") %>%
  filter(Metro == "South Bend-Mishawaka")

topTier <- read.csv("C:/Users/kost1/Documents/GitHub/DS-Now-Final-Project/Data Sources/City/City_Zhvi_TopTier.csv",
         stringsAsFactors = F) %>%
  filter(State == "IN") %>%
  filter(Metro == "South Bend-Mishawaka")
```

```{r}
bottomZillow <- bottomTier %>%
  gather(key = DateString,
         value = "Zillow Housing Value Index",
         -c(RegionID, RegionName, State, Metro, CountyName, SizeRank))

tidyBottomZillow <- bottomZillow %>%
  mutate(DateString = str_sub(DateString, start = 2)) %>%
  mutate(Date = as.Date(paste0(DateString, ".1"), "%Y.%m.%d") + months(1) - days(1))
```

```{r}
ggplot(
  data = na.omit(tidyBottomZillow),
  aes(x = Date, y = `Zillow Housing Value Index`, color = RegionName)
) + geom_point() + scale_y_continuous(labels = dollar_format()) +
  labs(x = "Date", y = "Zillow Housing Value Index",
       title = "Bottom Tier Housing Prices\nOver Time in South Bend Area",
       color = "City")
```
