---
title: "Final Deliverable"
author: "Joe Kosteck"
date: "March 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
setwd("~/GitHub/DS-Now-Final-Project/Final Deliverables")

library(tidycensus)
library(tidyverse)
library(leaflet)
library(rgdal)
library(DT)
library(rgeos)
library(sf)

load("cluster data for analysis.RData")
load("census_shapefiles.RData")
```

```{r, echo=FALSE, message=FALSE, results='hide'}
neighborhoods <- readOGR("./South_Bend_Active_Neighborhoods_Map",
                         layer = "Neighborhood_Boundaries-polygon",
                         stringsAsFactors = F)

neighborhoods$Name <- str_remove_all(neighborhoods$Name, "Â")
```
#County Wide Data
```{r, echo=FALSE, warning=FALSE}
block_shapes_profile <- block_shapes %>%
  inner_join(minus_margins_block, by = "NAME") %>%
  select(NAME, `Block Group`, `Census Tract`,
         Profile = cluster, geometry)

profile_block_pal <- colorFactor("Dark2", block_shapes$Profile)
profile_colors <- profile_block_pal(1:5)

block_shapes_profile$`Block Group` <- str_remove(block_shapes_profile$`Block Group`,
                                                 "Block Group ")

block_shapes_profile$`Census Tract` <- str_remove(block_shapes_profile$`Census Tract`,
                                                  "Census Tract ")

block_shapes_profile$name_popup <- paste0("<b>Profile: </b>",
                                          block_shapes_profile$Profile,
                                          "<br><b>Census Tract: </b>",
                                          block_shapes_profile$`Census Tract`,
                                          "<br><b>Block Group: </b>",
                                          block_shapes_profile$`Block Group`)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 1,],
              color = profile_colors[1],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 1") %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 2,],
              color = profile_colors[2],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 2") %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 3,],
              color = profile_colors[3],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 3") %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 4,],
              color = profile_colors[4],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 4") %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 5,],
              color = profile_colors[5],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 5") %>%
  addPolygons(data = neighborhoods,
              color = "black",
              fillOpacity = .4,
              opacity = 1,
              weight = 2,
              group = "Neighborhoods",
              label = ~Name) %>%
  addLegend(pal = profile_block_pal,
            values = block_shapes_profile$Profile) %>%
  addLayersControl(overlayGroups = c("Profile 1", "Profile 2", "Profile 3",
                                     "Profile 4", "Profile 5", "Neighborhoods"),
                   options = layersControlOptions(collapsed = FALSE),
                   position = "topleft")
```

```{r, echo=FALSE}
transposed_center_block <- as.data.frame(t(unscaled_centers_block))
colnames(transposed_center_block) <- paste0("Profile ", 1:5)
transposed_center_block <- round(transposed_center_block, 2)
transposed_center_block <- transposed_center_block[-1, ]
rownames(transposed_center_block) <- c("Average Population",
                                       "Average Housing Units",
                                       "Average Occupied Housing Units",
                                       "Average Vacant Housing Units",
                                       "Average Owner-Occupied Units",
                                       "Average Renter-Occupied Units",
                                       "Average Units for Rent",
                                       "Average Rented, Non-Occupied Units",
                                       "Average Units for Sale",
                                       "Average Sold, Non-Occupied Units",
                                       "25th Percentile Home Value",
                                       "50th Percentile Home Value",
                                       "75th Percentile Home Value",
                                       "Median Owner Cost - Mortgage",
                                       "Median Owner Cost - No Mortgage",
                                       "Median Owner Cost/Income - Mortgage",
                                       "Median Owner Cost/Income - No Mortgage",
                                       "Median Family Income",
                                       "Average White Population",
                                       "Average Black Population",
                                       "Average Native American Population",
                                       "Average Asian Population",
                                       "Average Pacific Islander Population",
                                       "Average Other Population",
                                       "Average Two or More Races Population",
                                       "Median Age",
                                       "Median Age - Male",
                                       "Median Age - Female",
                                       "Average Households",
                                       "Family Households",
                                       "Family Households - Married",
                                       "Family Households - Other",
                                       "Non-family Households",
                                       "Non-family Households - Alone",
                                       "Non-family Households - Not Alone",
                                       "Two Person Families",
                                       "Three Person Families",
                                       "Four Person Families",
                                       "Five Person Families",
                                       "Six Person Families",
                                       "7 or More Person Families",
                                       "1 Person Non-families",
                                       "2 Person Non-families",
                                       "3 Person Non-families",
                                       "4 Person Non-families",
                                       "5 Person Non-families",
                                       "6 Person Non-families",
                                       "7 or More Person Non-families",
                                       "Average Labor Force",
                                       "Civilian Labor Force",
                                       "Civilian Labor Force - Employed",
                                       "Civilian Labor Force - Unemployed",
                                       "Military Labor Force",
                                       "Non-Labor Force",
                                       "Education - No Schooling",
                                       "Education - Nursery School",
                                       "Education - Kindergarten",
                                       "Education - First Grade",
                                       "Education - Second Grade",
                                       "Education - Third Grade",
                                       "Education - Fourth Grade",
                                       "Education - Fifth Grade",
                                       "Education - Sixth Grade",
                                       "Education - Seventh Grade",
                                       "Education - Eighth Grade",
                                       "Education - Ninth Grade",
                                       "Education - Tenth Grade",
                                       "Education - Eleventh Grade",
                                       "Education - Twelfth Grade - No Diploma",
                                       "Education - High School Diploma",
                                       "Education - GED or Alternative",
                                       "Education - Less Than 1 Year College",
                                       "Education - More Than 1 Year Collage - No Degree",
                                       "Education - Associates Degree",
                                       "Education - Bachelors Degree",
                                       "Education - Masters Degree",
                                       "Education - Professional School Degree",
                                       "Education - Doctorate Degree",
                                       "Commute - Car, Truck or Van",
                                       "Commute - Drive Alone",
                                       "Commute - Carpool",
                                       "Commute - 2 Person Carpool",
                                       "Commute - 3 Person Carpool",
                                       "Commute - 4 Person Carpool",
                                       "Commute - 5 or 6 Person Carpool",
                                       "Commute - 7 or More Person Carpool",
                                       "Commute - Public Transportation",
                                       "Commute - Bus or Trolley",
                                       "Commute - Subway or Elevated Train",
                                       "Commute - Railroad Train",
                                       "Commute - Ferry Boat",
                                       "Commute - Taxi",
                                       "Commute - Motorcycle",
                                       "Commute - Bicycle",
                                       "Commute - Walk",
                                       "Commute - Other Means",
                                       "Commute - Work from Home",
                                       "Household Income - Less than $10,000",
                                       "Household Income - $10,000 - $14,999",
                                       "Household Income - $15,000 - $19,999",
                                       "Household Income - $20,000 - $24,999",
                                       "Household Income - $25,000 - $29,999",
                                       "Household Income - $30,000 - $34,999",
                                       "Household Income - $35,000 - $39,999",
                                       "Household Income - $40,000 - $44,999",
                                       "Household Income - $45,000 - $49,999",
                                       "Household Income - $50,000 - $59,999",
                                       "Household Income - $60,000 - $74,999",
                                       "Household Income - $75,000 - $99,999",
                                       "Household Income - $100,000 - $124,999",
                                       "Household Income - $125,000 - $149,999",
                                       "Household Income - $150,000 - $199,999",
                                       "Household Income - $200,000 or More",
                                       "Median Rent/Income",
                                       "Median Housing Cost",
                                       "Median Non-family Income",
                                       "Median Rent - No Bedrooms",
                                       "Median Rent - 1 Bedroom",
                                       "Median Rent - 2 Bedrooms",
                                       "Median Rent - 3 Bedrooms",
                                       "Median Rent - 4 Bedrooms",
                                       "Median Rent - 5 or More Bedrooms",
                                       "Median Rent",
                                       "Aggregate Income Deficit",
                                       "Aggregate Income Deficit - Married",
                                       "Aggregate Income Deficit - Nonmarried",
                                       "Aggregate Income Deficit - No Wife",
                                       "Aggregate Income Deficit - No Husband",
                                       "Median Household Income",
                                       "Median Household Income - Owners",
                                       "Median Household Income - Renters",
                                       "Commute - Streetcar or Trolley Car",
                                       "Empolyed - No Vehicles Available",
                                       "Empolyed - 1 Vehicle Available",
                                       "Empolyed - 2 Vehicles Available",
                                       "Empolyed - 3 Vehicles Available",
                                       "Empolyed - 4 Vehicles Available",
                                       "Empolyed - 5 Vehicles Available")
```

```{r, echo=FALSE}
datatable(transposed_center_block)
```

```{r, warning=FALSE, echo=FALSE}
spatial_block_shapes <- sf::as_Spatial(block_shapes_profile,
                                       IDs = block_shapes_profile$NAME)

proj4string(spatial_block_shapes) <- proj4string(neighborhoods)

overlap_matrix <- gOverlaps(neighborhoods,
                            spatial_block_shapes,
                            byid = T)
touches_matrix <- gTouches(neighborhoods,
                           spatial_block_shapes,
                           byid = T)

contains_matrix <- gContains(neighborhoods,
                             spatial_block_shapes,
                             byid = T)

crosses_matrix <- gCrosses(neighborhoods,
                           spatial_block_shapes,
                           byid = T)

index_matrix <- touches_matrix | overlap_matrix | contains_matrix | crosses_matrix

imputed_block$`Block Group` <- str_remove(imputed_block$`Block Group`,
                                          "Block Group ")

imputed_block$`Census Tract` <- str_remove(imputed_block$`Census Tract`,
                                           "Census Tract ")

block_tibble <- as.tibble(block_shapes_profile) %>%
  select(-geometry, name_popup)

neighborhood_touches <- NULL

for (i in 1:length(neighborhoods$Name)) {
  new_neighborhood <- block_tibble[index_matrix[, i], ] %>%
    inner_join(imputed_block, by = c("Block Group", "Census Tract"))
  
  if(nrow(new_neighborhood) > 0) {
    new_neighborhood$Neighborhood <- neighborhoods$Name[i]
    
    neighborhood_touches <- bind_rows(neighborhood_touches, new_neighborhood)
  }
}

```

```{r, echo=FALSE, warning=FALSE}
neighborhood_touches <- neighborhood_touches %>%
  select(-NAME, -name_popup, -cluster) %>%
  select(Neighborhood, Profile, everything())

neighborhood_touches_names <- c("Neighborhood",
                                "Profile",
                                "Block Group",
                                "Census Tract",
                                "Total Population",
                                "Total Housing Units",
                                "Total Occupied Housing Units",
                                "Total Vacant Housing Units",
                                "Total Owner-Occupied Units",
                                "Total Renter-Occupied Units",
                                "Total Units for Rent",
                                "Total Rented, Non-Occupied Units",
                                "Total Units for Sale",
                                "Total Sold, Non-Occupied Units",
                                "25th Percentile Home Value",
                                "50th Percentile Home Value",
                                "75th Percentile Home Value",
                                "Median Owner Cost - Mortgage",
                                "Median Owner Cost - No Mortgage",
                                "Median Owner Cost/Income - Mortgage",
                                "Median Owner Cost/Income - No Mortgage",
                                "Median Family Income",
                                "Total White Population",
                                "Total Black Population",
                                "Total Native American Population",
                                "Total Asian Population",
                                "Total Pacific Islander Population",
                                "Total Other Population",
                                "Total Two or More Races Population",
                                "Median Age",
                                "Median Age - Male",
                                "Median Age - Female",
                                "Total Households",
                                "Family Households",
                                "Family Households - Married",
                                "Family Households - Other",
                                "Non-family Households",
                                "Non-family Households - Alone",
                                "Non-family Households - Not Alone",
                                "Two Person Families",
                                "Three Person Families",
                                "Four Person Families",
                                "Five Person Families",
                                "Six Person Families",
                                "7 or More Person Families",
                                "1 Person Non-families",
                                "2 Person Non-families",
                                "3 Person Non-families",
                                "4 Person Non-families",
                                "5 Person Non-families",
                                "6 Person Non-families",
                                "7 or More Person Non-families",
                                "Average Labor Force",
                                "Civilian Labor Force",
                                "Civilian Labor Force - Employed",
                                "Civilian Labor Force - Unemployed",
                                "Military Labor Force",
                                "Non-Labor Force",
                                "Education - No Schooling",
                                "Education - Nursery School",
                                "Education - Kindergarten",
                                "Education - First Grade",
                                "Education - Second Grade",
                                "Education - Third Grade",
                                "Education - Fourth Grade",
                                "Education - Fifth Grade",
                                "Education - Sixth Grade",
                                "Education - Seventh Grade",
                                "Education - Eighth Grade",
                                "Education - Ninth Grade",
                                "Education - Tenth Grade",
                                "Education - Eleventh Grade",
                                "Education - Twelfth Grade - No Diploma",
                                "Education - High School Diploma",
                                "Education - GED or Alternative",
                                "Education - Less Than 1 Year College",
                                "Education - More Than 1 Year Collage - No Degree",
                                "Education - Associates Degree",
                                "Education - Bachelors Degree",
                                "Education - Masters Degree",
                                "Education - Professional School Degree",
                                "Education - Doctorate Degree",
                                "Commute - Car, Truck or Van",
                                "Commute - Drive Alone",
                                "Commute - Carpool",
                                "Commute - 2 Person Carpool",
                                "Commute - 3 Person Carpool",
                                "Commute - 4 Person Carpool",
                                "Commute - 5 or 6 Person Carpool",
                                "Commute - 7 or More Person Carpool",
                                "Commute - Public Transportation",
                                "Commute - Bus or Trolley",
                                "Commute - Subway or Elevated Train",
                                "Commute - Railroad Train",
                                "Commute - Ferry Boat",
                                "Commute - Taxi",
                                "Commute - Motorcycle",
                                "Commute - Bicycle",
                                "Commute - Walk",
                                "Commute - Other Means",
                                "Commute - Work from Home",
                                "Household Income - Less than $10,000",
                                "Household Income - $10,000 - $14,999",
                                "Household Income - $15,000 - $19,999",
                                "Household Income - $20,000 - $24,999",
                                "Household Income - $25,000 - $29,999",
                                "Household Income - $30,000 - $34,999",
                                "Household Income - $35,000 - $39,999",
                                "Household Income - $40,000 - $44,999",
                                "Household Income - $45,000 - $49,999",
                                "Household Income - $50,000 - $59,999",
                                "Household Income - $60,000 - $74,999",
                                "Household Income - $75,000 - $99,999",
                                "Household Income - $100,000 - $124,999",
                                "Household Income - $125,000 - $149,999",
                                "Household Income - $150,000 - $199,999",
                                "Household Income - $200,000 or More")

colnames(neighborhood_touches) <- neighborhood_touches_names

datatable(neighborhood_touches,
          options = list(
            scrollX = T
          )
)
```

```{r, echo=FALSE}
neighborhood_transposed <- neighborhood_touches %>%
  group_by(Neighborhood) %>%
  select_if(is.numeric) %>%
  select(-Profile) %>%
  summarise_all(mean) %>%
  t(.) %>%
  as.tibble()

colnames(neighborhood_transposed) <- neighborhood_transposed[1, ]
neighborhood_transposed <- neighborhood_transposed[-1, ]
neighborhood_transposed <- neighborhood_transposed %>%
  mutate_all(as.numeric) %>%
  round(., 3)

datatable(neighborhood_transposed,
          options = list(
            scrollX = TRUE
          ))
```

##Profile 1
```{r, warning=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 1,],
              color = profile_colors[1],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 1",
              label = "Profile 1")
```

##Profile 2
```{r, warning=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 2,],
              color = profile_colors[2],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 2",
              label = "Profile 2")
```

##Profile 3
```{r, warning=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 3,],
              color = profile_colors[3],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 3",
              label = "Profile 3")
```

##Profile 4
```{r, warning=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 4,],
              color = profile_colors[4],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 4",
              label = "Profile 4")
```

#Profile 5
```{r, warning=FALSE, echo=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = block_shapes_profile[block_shapes_profile$Profile == 5,],
              color = profile_colors[5],
              fillOpacity = .75,
              opacity = 1,
              popup = ~name_popup,
              group = "Profile 5",
              label = "Profile 5")
```